[package]
name = "celeste"
version = "0.8.3"
edition = "2024"
license = "GPL-3.0-or-later"
authors = [
    "Hunter Wittenborn <hunter@hunterwittenborn.com>",
    "Alexander Menzel <menzel.alexander@proton.me>",
]
repository = "https://github.com/hwittenborn/celeste"

[dependencies]
clap = { version = "4.5.7", features = ["derive", "env"] }
file-lock = "2.1.11"
futures = "0.3.30"
glob = "0.3.1"
iced = { version = "0.12", features = ["tokio"] }
librclone = { version = "0.6.3" }
sea-orm = { version = "0.10.7", features = ["sqlx-sqlite", "runtime-async-std-rustls", "macros"] }
sea-orm-migration = "0.10.7"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
time = { version = "0.3.36", features = ["serde-well-known"] }
tokio = { version = "1.38.0", features = ["macros", "rt-multi-thread", "sync"] }
tr = "0.1.7"

