//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.3, then trimmed by
//! hand — the `instant_sync` column has been removed along with the
//! fs_watcher.
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "remotes")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub sync_interval_seconds: i32,
    pub enabled: i32,
    pub last_sync_at: Option<i64>,
    pub last_sync_status: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::sync_dirs::Entity")]
    SyncDirs,
}

impl Related<super::sync_dirs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SyncDirs.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
